import { IPage } from "./IPage";
import { ICommunityPlatformSession } from "./ICommunityPlatformSession";

/**
 * Paginated collection of session entities according to IPage<T> contract. Used
 * for listing current, historical, or filtered session lists. Data array
 * contains one or more full ICommunityPlatformSession objects.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageICommunityPlatformSession = {
  pagination: IPage.IPagination;
  data: ICommunityPlatformSession[];
};
