import { IPage } from "./IPage";
import { ICommunityPlatformAuditLog } from "./ICommunityPlatformAuditLog";

/**
 * Paginated collection of community platform audit log records. Contains the
 * pagination info and data array of audit log objects.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageICommunityPlatformAuditLog = {
  pagination: IPage.IPagination;
  data: ICommunityPlatformAuditLog[];
};
