import { IPage } from "./IPage";
import { ICommunityPlatformPostReport } from "./ICommunityPlatformPostReport";

/**
 * Paginated collection of post report records. Includes pagination metadata and
 * array of ICommunityPlatformPostReport records. Used for moderation workflows,
 * reporting UIs, and system-level audit queries.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageICommunityPlatformPostReport = {
  pagination: IPage.IPagination;
  data: ICommunityPlatformPostReport[];
};
