import { IPage } from "./IPage";
import { ICommunityPlatformDataExportLog } from "./ICommunityPlatformDataExportLog";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageICommunityPlatformDataExportLog = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: ICommunityPlatformDataExportLog[];
};
