import { IPage } from "./IPage";
import { ICommunityPlatformAdminAction } from "./ICommunityPlatformAdminAction";

/**
 * Paginated collection of admin/moderation action records (audit log entries
 * for admin/mod actions). Includes the page information and results, following
 * the standard paginated object structure.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageICommunityPlatformAdminAction = {
  pagination: IPage.IPagination;
  data: ICommunityPlatformAdminAction[];
};
