import { IPage } from "./IPage";
import { ICommunityPlatformConfiguration } from "./ICommunityPlatformConfiguration";

/**
 * Paginated collection of configuration parameter results.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageICommunityPlatformConfiguration = {
  pagination: IPage.IPagination;

  /** Array with one element per configuration parameter in the result set. */
  data: ICommunityPlatformConfiguration[];
};
