import { IPage } from "./IPage";
import { ICommunityPlatformRecentCommunity } from "./ICommunityPlatformRecentCommunity";

/**
 * A page.
 *
 * Collection of records with pagination information.
 *
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export type IPageICommunityPlatformRecentCommunity = {
  /** Page information. */
  pagination: IPage.IPagination;

  /** List of records. */
  data: ICommunityPlatformRecentCommunity[];
};
