import { Controller } from "@nestjs/common";
import { TypedRoute, TypedParam, TypedBody } from "@nestia/core";
import typia, { tags } from "typia";
import { post__communityPlatform_memberUser_comments_$commentId_votes } from "../../../../../providers/post__communityPlatform_memberUser_comments_$commentId_votes";
import { MemberuserAuth } from "../../../../../decorators/MemberuserAuth";
import { MemberuserPayload } from "../../../../../decorators/payload/MemberuserPayload";
import { put__communityPlatform_memberUser_comments_$commentId_votes_$voteId } from "../../../../../providers/put__communityPlatform_memberUser_comments_$commentId_votes_$voteId";
import { delete__communityPlatform_memberUser_comments_$commentId_votes_$voteId } from "../../../../../providers/delete__communityPlatform_memberUser_comments_$commentId_votes_$voteId";

import { ICommunityPlatformCommentVote } from "../../../../../api/structures/ICommunityPlatformCommentVote";

@Controller("/communityPlatform/memberUser/comments/:commentId/votes")
export class CommunityplatformMemberuserCommentsVotesController {
  /**
   * Create a new vote (upvote/downvote) on a comment
   * (community_platform_comment_votes).
   *
   * This endpoint allows an authenticated user to cast an upvote or downvote on
   * a specific comment. Only valid vote types are accepted ('upvote',
   * 'downvote', or clearing vote with 'none'). The system ensures one record
   * per user per comment, creating or updating the user's vote as appropriate.
   *
   * Business logic enforces that users cannot vote on their own comments;
   * attempts to do so result in a permission error. On casting or updating a
   * vote, the vote_type, voter identity (memberUser or adminUser), timestamps,
   * and target comment are stored in the community_platform_comment_votes
   * table.
   *
   * Security is enforced so only the voting user (memberUser or adminUser) may
   * create their own votes. This operation is essential for the platform's
   * reputation and scoring system for comment engagement. Vote score
   * calculation is handled elsewhere.
   *
   * @param connection
   * @param commentId Unique identifier of the comment to vote on
   * @param body Vote object to be created with commentId, voter, and vote_type
   *   (upvote, downvote, none)
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async create(
    @MemberuserAuth()
    memberUser: MemberuserPayload,
    @TypedParam("commentId")
    commentId: string & tags.Format<"uuid">,
    @TypedBody()
    body: ICommunityPlatformCommentVote.ICreate,
  ): Promise<ICommunityPlatformCommentVote> {
    try {
      return await post__communityPlatform_memberUser_comments_$commentId_votes(
        {
          memberUser,
          commentId,
          body,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update the vote state for a comment vote
   * (community_platform_comment_votes).
   *
   * This endpoint allows the original voter (memberUser or adminUser) or an
   * admin to change the state of a vote on a comment, such as toggling
   * upvote/downvote or clearing to none. The operation validates that the
   * voteId is associated with the specified commentId, and that the user has
   * permission (voter = self or admin privilege).
   *
   * Validation ensures that users cannot vote on their own comments. State
   * transitions follow platform voting business logic: toggling between upvote,
   * downvote, and none. Updated_at is changed to reflect the most recent
   * action, with full support for audit/compliance. Errors are returned for
   * invalid vote states, permission failures, or mismatched IDs.
   *
   * @param connection
   * @param commentId Unique identifier of the target comment
   * @param voteId Unique identifier of the comment vote to update
   * @param body Fields to update in the comment vote (vote_type: upvote,
   *   downvote, none)
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put(":voteId")
  public async update(
    @MemberuserAuth()
    memberUser: MemberuserPayload,
    @TypedParam("commentId")
    commentId: string & tags.Format<"uuid">,
    @TypedParam("voteId")
    voteId: string & tags.Format<"uuid">,
    @TypedBody()
    body: ICommunityPlatformCommentVote.IUpdate,
  ): Promise<ICommunityPlatformCommentVote> {
    try {
      return await put__communityPlatform_memberUser_comments_$commentId_votes_$voteId(
        {
          memberUser,
          commentId,
          voteId,
          body,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Delete a comment vote (community_platform_comment_votes).
   *
   * This endpoint allows the original voter (memberUser or adminUser) or a
   * platform admin to remove a vote they have cast on a comment. By deleting
   * the vote record (hard delete), the platform forgets the user's vote state
   * for the targeted comment. The database table is
   * community_platform_comment_votes.
   *
   * The operation validates that the provided voteId is linked to the specified
   * commentId, and ensures that only the original voter or admin has permission
   * to delete. This operation is commonly used to allow users to retract their
   * upvote/downvote, and also serves as a moderation tool for platform
   * administrators. No content is returned in the response upon successful
   * deletion.
   *
   * @param connection
   * @param commentId Unique identifier of the parent comment
   * @param voteId Unique identifier of the comment vote to delete
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":voteId")
  public async erase(
    @MemberuserAuth()
    memberUser: MemberuserPayload,
    @TypedParam("commentId")
    commentId: string & tags.Format<"uuid">,
    @TypedParam("voteId")
    voteId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await delete__communityPlatform_memberUser_comments_$commentId_votes_$voteId(
        {
          memberUser,
          commentId,
          voteId,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
