import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ICommunityPlatformMemberUser } from "../../../../structures/ICommunityPlatformMemberUser";
import { IPageICommunityPlatformMemberUser } from "../../../../structures/IPageICommunityPlatformMemberUser";

/**
 * Search and paginate member user accounts (community_platform_memberusers).
 *
 * Returns a paginated set of member users (registered user accounts) filtered
 * by display name, account status, or creation/update timestamps, as defined in
 * the Prisma model community_platform_memberusers. This operation allows admins
 * to monitor, search, and manage the user base, applying business logic for
 * name/status searching, sort order, and precise pagination.
 *
 * Only admin users are granted access due to the privacy-sensitive nature of
 * user account data. The search supports partial matching for display names,
 * status filtering, and date range controls. Pagination is enforced with
 * efficient sorting according to primary business needs. If search criteria are
 * invalid or missing, descriptive error messages are returned. May be used for
 * admin user management, compliance review, or platform analytics dashboards.
 *
 * For efficiency and privacy, only summary fields are returned in paginated
 * lists; full detail may be fetched via other admin endpoints as needed. Audit
 * logging for query access is recommended for legal/compliance review.
 *
 * @param props.connection
 * @param props.body Pagination, filter, and search criteria for member user
 *   accounts.
 * @path /communityPlatform/adminUser/memberUsers
 * @accessor api.functional.communityPlatform.adminUser.memberUsers.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /** Pagination, filter, and search criteria for member user accounts. */
    body: ICommunityPlatformMemberUser.IRequest;
  };
  export type Body = ICommunityPlatformMemberUser.IRequest;
  export type Response = IPageICommunityPlatformMemberUser.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/communityPlatform/adminUser/memberUsers",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/communityPlatform/adminUser/memberUsers";
  export const random = (): IPageICommunityPlatformMemberUser.ISummary =>
    typia.random<IPageICommunityPlatformMemberUser.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Get detailed member user information by ID (community_platform_memberusers).
 *
 * This endpoint allows retrieval of a member user's complete profile and
 * related attributes given their unique identifier, as defined in the
 * community_platform_memberusers Prisma model.
 *
 * It is used for backend logic and UI features such as profile display, author
 * information on posts and comments, and eligibility for content actions. Only
 * authenticated users and platform admins may use this endpoint, in compliance
 * with business access rules and privacy context.
 *
 * The returned object includes display name, status, timestamps, and all
 * business logic-required attributes. Related information from referencing
 * tables (e.g. posts, comments, community memberships) may be used by clients
 * to contextualize the user's activity footprint.
 *
 * If the requested member user does not exist or access is denied due to
 * authorization constraints, a 404 or appropriate error response is provided.
 *
 * @param props.connection
 * @param props.memberUserId Unique identifier of the member user to retrieve.
 * @path /communityPlatform/adminUser/memberUsers/:memberUserId
 * @accessor api.functional.communityPlatform.adminUser.memberUsers.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** Unique identifier of the member user to retrieve. */
    memberUserId: string & tags.Format<"uuid">;
  };
  export type Response = ICommunityPlatformMemberUser;

  export const METADATA = {
    method: "GET",
    path: "/communityPlatform/adminUser/memberUsers/:memberUserId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/communityPlatform/adminUser/memberUsers/${encodeURIComponent(props.memberUserId ?? "null")}`;
  export const random = (): ICommunityPlatformMemberUser =>
    typia.random<ICommunityPlatformMemberUser>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("memberUserId")(() => typia.assert(props.memberUserId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
