import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ICommunityPlatformVote } from "../../../../structures/ICommunityPlatformVote";
import { IPageICommunityPlatformVote } from "../../../../structures/IPageICommunityPlatformVote";

/**
 * Create or update a vote for a post or comment.
 *
 * Create or update a user's vote on a specified post or comment. Only one vote
 * per user-target is retained; submitting a new vote overwrites any prior. The
 * value may be 1 (upvote), -1 (downvote), or 0 (neutral/remove vote state).
 * Voting on own content is forbidden in business logic and checked at request
 * time.
 *
 * Duplicate or conflicting votes are resolved by keeping the latest state.
 * Unauthorized or illogical attempts (e.g., voting on non-existent or own
 * content) result in standard error responses. On success, full vote record is
 * returned.
 *
 * @param props.connection
 * @param props.body Vote creation info: voter, target post/comment, and vote
 *   value
 * @path /communityPlatform/member/votes
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function create(
  connection: IConnection,
  props: create.Props,
): Promise<create.Response> {
  return true === connection.simulate
    ? create.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...create.METADATA,
          path: create.path(),
          status: null,
        },
        props.body,
      );
}
export namespace create {
  export type Props = {
    /** Vote creation info: voter, target post/comment, and vote value */
    body: ICommunityPlatformVote.ICreate;
  };
  export type Body = ICommunityPlatformVote.ICreate;
  export type Response = ICommunityPlatformVote;

  export const METADATA = {
    method: "POST",
    path: "/communityPlatform/member/votes",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/communityPlatform/member/votes";
  export const random = (): ICommunityPlatformVote =>
    typia.random<ICommunityPlatformVote>();
  export const simulate = (
    connection: IConnection,
    props: create.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: create.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Retrieve paginated, filtered vote records across posts and comments.
 *
 * Return a paginated list of votes cast by users on posts and comments. This
 * API supports advanced filters including by voter, post/comment, vote value
 * (up, down, neutral), and timestamp ranges for reviewing platform activity or
 * personal voting history.
 *
 * Access control permits admins to view all voting records, while members may
 * only retrieve their own. Pagination, searching, and sorting allow efficient
 * bulk review or individual account history. Proper error handling is provided
 * for invalid filters or unauthorized access attempts.
 *
 * @param props.connection
 * @param props.body Advanced filter, search, and pagination criteria for votes
 * @path /communityPlatform/member/votes
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /** Advanced filter, search, and pagination criteria for votes */
    body: ICommunityPlatformVote.IRequest;
  };
  export type Body = ICommunityPlatformVote.IRequest;
  export type Response = IPageICommunityPlatformVote.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/communityPlatform/member/votes",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/communityPlatform/member/votes";
  export const random = (): IPageICommunityPlatformVote.ISummary =>
    typia.random<IPageICommunityPlatformVote.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Get detailed voting record by voteId.
 *
 * Returns a single voting record including full field data: who voted, the
 * target (post or comment), vote value, and creation/update metadata. Useful
 * for per-user or moderation review. Access is restricted by role.
 *
 * Errors are returned for requests with invalid or unauthorized vote IDs.
 * Common usage includes review of individual voting actions or for platform
 * moderation purposes.
 *
 * @param props.connection
 * @param props.voteId The unique identifier (UUID) of the vote record
 * @path /communityPlatform/member/votes/:voteId
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /** The unique identifier (UUID) of the vote record */
    voteId: string & tags.Format<"uuid">;
  };
  export type Response = ICommunityPlatformVote;

  export const METADATA = {
    method: "GET",
    path: "/communityPlatform/member/votes/:voteId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/communityPlatform/member/votes/${encodeURIComponent(props.voteId ?? "null")}`;
  export const random = (): ICommunityPlatformVote =>
    typia.random<ICommunityPlatformVote>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("voteId")(() => typia.assert(props.voteId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Update a user's existing vote on a post or comment in the community platform.
 *
 * This operation allows a logged-in user to update their own vote on a post or
 * comment. It accepts the unique vote ID as a path parameter, checks that the
 * authenticated user is the owner of the vote (unless an admin override is
 * present), and updates the vote's value to either upvote (1), downvote (-1),
 * or none (0). The vote update is tracked with an updated_at timestamp for
 * audit compliance and history. Appropriate business logic is enforced to
 * prevent users from updating votes on their own content or multiple votes per
 * target. Admin users may update votes for moderation. The changed vote value
 * is instantly reflected in the net score and UI state.
 *
 * @param props.connection
 * @param props.voteId Unique ID of the vote to update.
 * @param props.body Updated vote information (vote value as 1, -1 or 0, and
 *   target identifiers).
 * @path /communityPlatform/member/votes/:voteId
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function update(
  connection: IConnection,
  props: update.Props,
): Promise<update.Response> {
  return true === connection.simulate
    ? update.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...update.METADATA,
          path: update.path(props),
          status: null,
        },
        props.body,
      );
}
export namespace update {
  export type Props = {
    /** Unique ID of the vote to update. */
    voteId: string & tags.Format<"uuid">;

    /**
     * Updated vote information (vote value as 1, -1 or 0, and target
     * identifiers).
     */
    body: ICommunityPlatformVote.IUpdate;
  };
  export type Body = ICommunityPlatformVote.IUpdate;
  export type Response = ICommunityPlatformVote;

  export const METADATA = {
    method: "PUT",
    path: "/communityPlatform/member/votes/:voteId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Omit<Props, "body">) =>
    `/communityPlatform/member/votes/${encodeURIComponent(props.voteId ?? "null")}`;
  export const random = (): ICommunityPlatformVote =>
    typia.random<ICommunityPlatformVote>();
  export const simulate = (
    connection: IConnection,
    props: update.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: update.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("voteId")(() => typia.assert(props.voteId));
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Soft-delete (remove) a user's vote on a post or comment.
 *
 * This operation allows an authenticated user to remove (soft-delete) their own
 * vote on a post or comment, or for an admin to remove a user's vote as part of
 * moderation. It uses the vote's unique ID as a path parameter, checks business
 * rules for permission (ownership/admin), and sets the deleted_at timestamp for
 * soft deletion. The operation is tracked in audit logs and affects the live
 * score displayed for the target post or comment.
 *
 * @param props.connection
 * @param props.voteId Unique ID of the vote to remove (soft delete).
 * @path /communityPlatform/member/votes/:voteId
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function erase(
  connection: IConnection,
  props: erase.Props,
): Promise<void> {
  return true === connection.simulate
    ? erase.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...erase.METADATA,
          path: erase.path(props),
          status: null,
        },
      );
}
export namespace erase {
  export type Props = {
    /** Unique ID of the vote to remove (soft delete). */
    voteId: string & tags.Format<"uuid">;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/communityPlatform/member/votes/:voteId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/communityPlatform/member/votes/${encodeURIComponent(props.voteId ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (
    connection: IConnection,
    props: erase.Props,
  ): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: erase.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("voteId")(() => typia.assert(props.voteId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
