import { Controller } from "@nestjs/common";
import { TypedRoute, TypedBody, TypedParam } from "@nestia/core";
import typia, { tags } from "typia";
import { post__communityPlatform_member_posts } from "../../../../providers/post__communityPlatform_member_posts";
import { MemberAuth } from "../../../../decorators/MemberAuth";
import { MemberPayload } from "../../../../decorators/payload/MemberPayload";
import { put__communityPlatform_member_posts_$postId } from "../../../../providers/put__communityPlatform_member_posts_$postId";
import { delete__communityPlatform_member_posts_$postId } from "../../../../providers/delete__communityPlatform_member_posts_$postId";

import { ICommunityPlatformPost } from "../../../../api/structures/ICommunityPlatformPost";

@Controller("/communityPlatform/member/posts")
export class CommunityplatformMemberPostsController {
  /**
   * Create a new post in a community by an authenticated member.
   *
   * This operation allows any authenticated member to create a new post within
   * a specific community. Based on the community_platform_posts table, all
   * required information—including the community id, author/member id, post
   * title (5-120 characters, plain text only), body (10-10,000 characters,
   * plain text only), and optional author_display_name—must be provided in the
   * request. Upon validation, a new post is created and persisted with
   * created_at and updated_at timestamps. The operation enforces all input
   * validation rules (lengths, content policies, and foreign key integrity for
   * community and member). The resulting entity is linked to its community and
   * author; downstream operations such as commenting, voting, and editing are
   * allowed. This operation is secured by requiring member authentication and
   * does not allow public or guest access. Error scenarios include missing or
   * invalid fields, lack of authentication, or violations of business rules
   * regarding post structure or membership. Upon success, the full created post
   * entity is returned, matching the schema definition.
   *
   * @param connection
   * @param body Information required to create a new community post, according
   *   to schema and business rules.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Post()
  public async create(
    @MemberAuth()
    member: MemberPayload,
    @TypedBody()
    body: ICommunityPlatformPost.ICreate,
  ): Promise<ICommunityPlatformPost> {
    try {
      return await post__communityPlatform_member_posts({
        member,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Update an existing community post by postId, with strict validation and
   * role checks.
   *
   * This endpoint updates a post’s editable fields (title, body,
   * author_display_name) as defined in the community_platform_posts schema. It
   * requires authentication as the post author or admin, and strictly enforces
   * input validation. The updated content is persisted, timestamps are updated,
   * and a corresponding post_snapshot is generated for version history. The
   * operation does not allow updates to the post's community, author, or unique
   * id. If the target post does not exist, was deleted, or the user is not
   * authorized, a suitable error is returned. This endpoint is fundamental for
   * member-driven content management and editorial workflows in the platform
   * business domain. Other modification actions, such as moderation or post
   * restoration, are handled in separate administrative endpoints. API
   * consumers should ensure that edit/update shapes match the server's required
   * DTO and all business and schema rules.
   *
   * @param connection
   * @param postId The unique identifier (UUID) of the post to update.
   * @param body Fields to update in the specified post, following business
   *   input rules.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Put(":postId")
  public async update(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("postId")
    postId: string & tags.Format<"uuid">,
    @TypedBody()
    body: ICommunityPlatformPost.IUpdate,
  ): Promise<ICommunityPlatformPost> {
    try {
      return await put__communityPlatform_member_posts_$postId({
        member,
        postId,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Soft delete the specified community post by postId (set deleted_at).
   *
   * This operation soft deletes a specific post on the community platform,
   * setting the 'deleted_at' column of community_platform_posts. Only the
   * post's author or an admin is permitted to perform this action. Soft
   * deletion ensures the post is hidden from the main feed but remains in the
   * database for compliance, audit, and possible future restoration. Comments,
   * votes, and related moderation data must be handled as per cascade rules in
   * business logic (e.g., marking associated comments as deleted). Deleting a
   * non-existent, already-deleted, or unauthorized post results in an error.
   * This endpoint does not support hard deletion or data purging, and is
   * consistent with audit, moderation, and compliance workflows. Soft-deleted
   * posts are not returned by most read/search operations. Restoration
   * (undelete) is performed via different admin endpoints if allowed by
   * business policy.
   *
   * @param connection
   * @param postId The unique identifier (UUID) of the post to delete (soft
   *   delete).
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Delete(":postId")
  public async erase(
    @MemberAuth()
    member: MemberPayload,
    @TypedParam("postId")
    postId: string & tags.Format<"uuid">,
  ): Promise<void> {
    try {
      return await delete__communityPlatform_member_posts_$postId({
        member,
        postId,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
