import { Controller } from "@nestjs/common";
import { TypedRoute, TypedBody, TypedParam } from "@nestia/core";
import typia, { tags } from "typia";
import { patch__communityPlatform_adminUser_dataExportLogs } from "../../../../providers/patch__communityPlatform_adminUser_dataExportLogs";
import { AdminuserAuth } from "../../../../decorators/AdminuserAuth";
import { AdminuserPayload } from "../../../../decorators/payload/AdminuserPayload";
import { get__communityPlatform_adminUser_dataExportLogs_$dataExportLogId } from "../../../../providers/get__communityPlatform_adminUser_dataExportLogs_$dataExportLogId";

import { IPageICommunityPlatformDataExportLog } from "../../../../api/structures/IPageICommunityPlatformDataExportLog";
import { ICommunityPlatformDataExportLog } from "../../../../api/structures/ICommunityPlatformDataExportLog";

@Controller("/communityPlatform/adminUser/dataExportLogs")
export class CommunityplatformAdminuserDataexportlogsController {
  /**
   * Search, filter, and paginate data export logs
   * (community_platform_data_export_logs) for compliance and audit purposes.
   *
   * This API endpoint enables adminUsers to perform advanced search, filtering,
   * and pagination across all data export logs in the system. Each data export
   * log records a member or admin's request for exportable data, tracking the
   * export type (user data, community data, posts, etc.), format, requesting
   * user, status, and timestamps as defined in the
   * community_platform_data_export_logs table.
   *
   * Security is prioritized: only adminUser roles may invoke this operation,
   * protecting sensitive compliance and audit information. The endpoint
   * supports optional search parameters for filtering by user, admin, export
   * type, status, and date range, as defined in the request body DTO. Complex
   * queries are supported for in-depth compliance reviews, operational
   * oversight, and legal investigation flows.
   *
   * The list is paginated and sorted according to supplied criteria in the
   * request. Results exclude records that have been soft-deleted per compliance
   * policy. Related operations include retrieval of individual export log
   * records or search log analytics for broader platform oversight.
   *
   * @param connection
   * @param body Advanced search and pagination criteria for data export log
   *   listing, including user/admin, export type, status, and time range
   *   filters.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Patch()
  public async index(
    @AdminuserAuth()
    adminUser: AdminuserPayload,
    @TypedBody()
    body: ICommunityPlatformDataExportLog.IRequest,
  ): Promise<IPageICommunityPlatformDataExportLog> {
    try {
      return await patch__communityPlatform_adminUser_dataExportLogs({
        adminUser,
        body,
      });
    } catch (error) {
      console.log(error);
      throw error;
    }
  }

  /**
   * Retrieve detailed information for a specific data export log entry
   * (community_platform_data_export_logs).
   *
   * This API endpoint enables an authorized adminUser to fetch all recorded
   * details for a single data export log, using the dataExportLogId path
   * parameter. As defined in the community_platform_data_export_logs table,
   * each export log includes information about the type of export (user data,
   * community data, etc.), export format, user/admin requestor, status,
   * timestamps, and associated metadata crucial for regulatory compliance and
   * security audit trails.
   *
   * Access is strictly limited to adminUser roles because data export
   * activities may include sensitive user/member/admin data. The endpoint
   * checks for the existence and non-soft-deleted status of the referenced
   * export log record. If it is missing or soft-deleted, a not found error is
   * returned.
   *
   * This operation is generally used for compliance verification, security
   * investigations, or legal reporting, and may be paired with list/search
   * operations for complete audit coverage. Returned data includes all fields
   * of the export log, with certain fields (e.g., status, request IP) redacted
   * if required by business policy.
   *
   * @param connection
   * @param dataExportLogId Unique identifier of the data export log to
   *   retrieve.
   * @nestia Generated by Nestia - https://github.com/samchon/nestia
   */
  @TypedRoute.Get(":dataExportLogId")
  public async at(
    @AdminuserAuth()
    adminUser: AdminuserPayload,
    @TypedParam("dataExportLogId")
    dataExportLogId: string & tags.Format<"uuid">,
  ): Promise<ICommunityPlatformDataExportLog> {
    try {
      return await get__communityPlatform_adminUser_dataExportLogs_$dataExportLogId(
        {
          adminUser,
          dataExportLogId,
        },
      );
    } catch (error) {
      console.log(error);
      throw error;
    }
  }
}
