import { IConnection, HttpError } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia, { tags } from "typia";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";

import { ICommunityPlatformCategory } from "../../../../structures/ICommunityPlatformCategory";
import { IPageICommunityPlatformCategory } from "../../../../structures/IPageICommunityPlatformCategory";

/**
 * Search and list community platform categories with filtering and pagination.
 *
 * Retrieve a list of categories from the community_platform_categories table,
 * enabling advanced filters by name, description (with GIN/trigram search
 * optimizations), and display_order. Pagination and sorting options are
 * supported as per system-wide listing standards. This operation allows
 * authenticated users (adminUser/memberUser) to discover categories for
 * community creation or UI selector purposes.
 *
 * The API response contains summary data for each category, such as ID, name,
 * display order, optional description, timestamps, and all fields defined in
 * the Prisma schema, enabling frontend typeahead, dropdowns, and management
 * interfaces.
 *
 * Permissions: This operation is available to both adminUser and memberUser
 * roles. It does not expose any sensitive data and is suitable for public
 * category listings. Error handling covers validation of search queries and
 * response limits to prevent abusive or nonsensical lookups.
 *
 * @param props.connection
 * @param props.body Search and filter criteria for categories, including
 *   name/description match, sorting, and paging.
 * @path /communityPlatform/memberUser/categories
 * @accessor api.functional.communityPlatform.memberUser.categories.index
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function index(
  connection: IConnection,
  props: index.Props,
): Promise<index.Response> {
  return true === connection.simulate
    ? index.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...index.METADATA,
          path: index.path(),
          status: null,
        },
        props.body,
      );
}
export namespace index {
  export type Props = {
    /**
     * Search and filter criteria for categories, including name/description
     * match, sorting, and paging.
     */
    body: ICommunityPlatformCategory.IRequest;
  };
  export type Body = ICommunityPlatformCategory.IRequest;
  export type Response = IPageICommunityPlatformCategory.ISummary;

  export const METADATA = {
    method: "PATCH",
    path: "/communityPlatform/memberUser/categories",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = () => "/communityPlatform/memberUser/categories";
  export const random = (): IPageICommunityPlatformCategory.ISummary =>
    typia.random<IPageICommunityPlatformCategory.ISummary>();
  export const simulate = (
    connection: IConnection,
    props: index.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: index.path(),
      contentType: "application/json",
    });
    try {
      assert.body(() => typia.assert(props.body));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}

/**
 * Get details for a category by categoryId (UUID) from
 * community_platform_categories.
 *
 * Obtains a single category by its unique identifier from the
 * community_platform_categories table. The response includes the primary key,
 * name, display order, description, and timestamps as per the Prisma schema.
 *
 * Permissions: Both adminUser and memberUser are permitted. This is suitable
 * for populating category edit dialogs or detailed UI category displays.
 *
 * Security: Exposes only non-sensitive business dictionary data, restricted by
 * access roles. Errors include not found (if the UUID does not match any row).
 *
 * @param props.connection
 * @param props.categoryId Unique identifier for the target category
 *   (community_platform_categories.id).
 * @path /communityPlatform/memberUser/categories/:categoryId
 * @accessor api.functional.communityPlatform.memberUser.categories.at
 * @autobe Generated by AutoBE - https://github.com/wrtnlabs/autobe
 */
export async function at(
  connection: IConnection,
  props: at.Props,
): Promise<at.Response> {
  return true === connection.simulate
    ? at.simulate(connection, props)
    : await PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...at.METADATA,
          path: at.path(props),
          status: null,
        },
      );
}
export namespace at {
  export type Props = {
    /**
     * Unique identifier for the target category
     * (community_platform_categories.id).
     */
    categoryId: string & tags.Format<"uuid">;
  };
  export type Response = ICommunityPlatformCategory;

  export const METADATA = {
    method: "GET",
    path: "/communityPlatform/memberUser/categories/:categoryId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
  } as const;

  export const path = (props: Props) =>
    `/communityPlatform/memberUser/categories/${encodeURIComponent(props.categoryId ?? "null")}`;
  export const random = (): ICommunityPlatformCategory =>
    typia.random<ICommunityPlatformCategory>();
  export const simulate = (
    connection: IConnection,
    props: at.Props,
  ): Response => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: at.path(props),
      contentType: "application/json",
    });
    try {
      assert.param("categoryId")(() => typia.assert(props.categoryId));
    } catch (exp) {
      if (!typia.is<HttpError>(exp)) throw exp;
      return {
        success: false,
        status: exp.status,
        headers: exp.headers,
        data: exp.toJSON().message,
      } as any;
    }
    return random();
  };
}
